exclude: 'wip'
repos:
- repo: https://github.com/ambv/black
  rev: 23.3.0
  hooks:
    - id: black
      name: black-py
- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.2
  hooks:
  -   id: pyupgrade
      name: pyupgrade-py